# Generated by Django 5.1.3 on 2025-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('education_qualification', models.CharField(max_length=200)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
